// 'use client'

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Footer from "./component/Footer";
import Navbar from "./navbar/page";
import { Analytics } from "@vercel/analytics/react";
import { UserProvider } from "./context/UserContext";
// import CheckContext from "./checkContext/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <Navbar />
          {children}
          <Analytics />
          <Footer />
          <Toaster />
        </UserProvider>
      </body>
    </html>
  );
}
