// 'use client'


import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast';
import Footer from './component/Footer';
import Navbar from "./navbar/page";
import { Analytics } from '@vercel/analytics/react'
import  { UserProvider } from './context/UserContext';
import CheckContext from './checkContext/page';


// import ChakraUiProviders from './component/ChakraUiProviders';
// import { CacheProvider } from '@chakra-ui/next-js';
// import { ChakraProvider } from '@chakra-ui/react';
// import axios from "axios";
// import { useEffect, useState } from "react";
// import Hamburger from './component/Hamburger';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // const { user } = useUser();

  // interface User {
  //   username: string;
  //   email: string;
  //   isAdmin: boolean;
  // }
  //  const [user, setUser] = useState<User | null>(null);
  // useEffect(() => {
  //   getUserDetails();
  // }, []);
  // const getUserDetails = async () => {
  //   const res = await axios.get("/api/users/me");
  //   console.log("profiledata",res.data.data.isAdmin);
  //   setUser(res.data.data);
  // };

  return (
    <html lang="en">
      <body >

      {/* <CacheProvider>
      <ChakraProvider> */}

      {/* <ChakraUiProviders> */}
       <UserProvider>
        <Navbar />
        {/* {
          user?.isAdmin === true ? <Hamburger/> : ""
        } */}
        {children}
        <Analytics />
        <Footer/>
        <Toaster />
        </ UserProvider>

      {/* </ChakraUiProviders> */}
      

        {/* </ChakraProvider>
    </CacheProvider> */}
      </body>
    </html>
  )
}
